import { MemberStatus, TeamMember } from "../types";

import { ad, am, bb, cr, cs, dc, ds, jp, jv, rp } from "./images";

export const teamMembers: TeamMember[] = [
  {
    id: 1,
    firstName: "Jared",
    lastName: "Vance",
    photoUrl: jv,
    jiraId: "6279c3f123d61e006fc419ad",
    position: "Software Engineer 2",
    status: MemberStatus.None,
    notes: "",
    hasBeenViewed: false,
  },
  {
    id: 2,
    firstName: "Randi",
    lastName: "Prince",
    photoUrl: rp,
    jiraId: "712020:7376fb19-3b5e-4b6a-a917-7d592d5e3c63",
    position: "Software Engineer 2",
    status: MemberStatus.None,
    notes: "",
    hasBeenViewed: false,
  },
  {
    id: 3,
    firstName: "Jake",
    lastName: "Pennington",
    photoUrl: jp,
    jiraId: "5ec1e475c2e9a00c28b31ac5",
    position: "Senior Software Engineer",
    status: MemberStatus.None,
    notes: "",
    hasBeenViewed: false,
  },
  {
    id: 4,
    firstName: "Angela",
    lastName: "Dye",
    photoUrl: ad,
    jiraId: "557058:1ba1111b-5864-4157-89dc-21f37a6f4fd8",
    position: "QA Engineer",
    status: MemberStatus.None,
    notes: "",
    hasBeenViewed: false,
  },
  {
    id: 5,
    firstName: "Brody",
    lastName: "Binks",
    photoUrl: bb,
    jiraId: "712020:34911af8-48bb-4e47-90ed-312064bb9522",
    position: "Senior Software Engineer",
    status: MemberStatus.None,
    notes: "",
    hasBeenViewed: false,
  },
  {
    id: 6,
    firstName: "Chris",
    lastName: "Russon",
    photoUrl: cr,
    jiraId: "712020:0726456e-714f-45f4-ac25-9ba95929ab86",
    position: "Senior Product Manager",
    status: MemberStatus.None,
    notes: "",
    hasBeenViewed: false,
  },
  {
    id: 7,
    firstName: "Clayton",
    lastName: "Sharp",
    photoUrl: cs,
    jiraId: "712020:a178e327-d042-4614-bf95-9323e1f3c54b",
    position: "Software Developer",
    status: MemberStatus.None,
    notes: "",
    hasBeenViewed: false,
  },
  {
    id: 8,
    firstName: "Dave",
    lastName: "Summers",
    photoUrl: ds,
    jiraId: "5b928bb1d5f27c2c1933d447",
    position: "Engineering Manager",
    status: MemberStatus.None,
    notes: "",
    hasBeenViewed: false,
  },
  {
    id: 9,
    firstName: "Devin",
    lastName: "Cameron",
    photoUrl: dc,
    jiraId: "60458bd7e19f910069247cce",
    position: "Senior Product Designer",
    status: MemberStatus.None,
    notes: "",
    hasBeenViewed: false,
  },
  {
    id: 10,
    firstName: "Abdul",
    lastName: "Mansoor",
    photoUrl: am,
    jiraId: "712020:a151da26-cbdc-4e21-8290-e6fc2c1b341e",
    position: "Software Developer, Intern",
    status: MemberStatus.None,
    notes: "",
    hasBeenViewed: false,
  }
];
